# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-gbcontainer-27

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: crjgb27.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_BFB742DA1F144A93A8FC6C02DABD0C19 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_9B3DB6FA1A034557A6778AEEF64C212D }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: crjgb27.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_BFB742DA1F144A93A8FC6C02DABD0C19 }}/guestbook:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-gbcontainer-27'
          slot-name: 'staging'
          images: 'crjgb27.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_BFB742DA1F144A93A8FC6C02DABD0C19 }}/guestbook:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B437F5532DFA448BB7647BE2DE50313E }}